canciones = [
    {"song": "Billie Jean", "artist": "Michael Jackson", "album": "Thriller"},
    {"song": "Like a Prayer", "artist": "Madonna", "album": "Like a Prayer"},
    {"song": "Sweet Child O' Mine", "artist": "Guns N' Roses", "album": "Appetite for Destruction"},
    {"song": "Every Breath You Take", "artist": "The Police", "album": "Synchronicity"},
    {"song": "Take On Me", "artist": "a-ha", "album": "Hunting High and Low"},
    {"song": "With or Without You", "artist": "U2", "album": "The Joshua Tree"},
    {"song": "Livin' on a Prayer", "artist": "Bon Jovi", "album": "Slippery When Wet"},
    {"song": "Smells Like Teen Spirit", "artist": "Nirvana", "album": "Nevermind"},
    {"song": "Wonderwall", "artist": "Oasis", "album": "(What's the Story) Morning Glory?"},
    {"song": "Creep", "artist": "Radiohead", "album": "Pablo Honey"},
    {"song": "La Flaca", "artist": "Jarabe de Palo", "album": "La Flaca"},
    {"song": "Rayando el Sol", "artist": "Maná", "album": "Falta Amor"},
    {"song": "De Música Ligera", "artist": "Soda Stereo", "album": "Canción Animal"},
    {"song": "Persiana Americana", "artist": "Soda Stereo", "album": "Signos"},
    {"song": "Lamento Boliviano", "artist": "Enanitos Verdes", "album": "Big Bang"},
    {"song": "Matador", "artist": "Los Fabulosos Cadillacs", "album": "Vasos Vacíos"},
    {"song": "Corazón Espinado", "artist": "Santana ft. Maná", "album": "Supernatural"},
    {"song": "Oye Mi Amor", "artist": "Maná", "album": "¿Dónde Jugarán los Niños?"},
    {"song": "Entre Dos Tierras", "artist": "Héroes del Silencio", "album": "Senderos de Traición"},
    {"song": "Nada Valgo Sin Tu Amor", "artist": "Juanes", "album": "Mi Sangre"},
    {"song": "Hips Don't Lie", "artist": "Shakira ft. Wyclef Jean", "album": "Oral Fixation, Vol. 2"},
    {"song": "Whenever, Wherever", "artist": "Shakira", "album": "Laundry Service"},
    {"song": "Gasolina", "artist": "Daddy Yankee", "album": "Barrio Fino"},
    {"song": "Danza Kuduro", "artist": "Don Omar", "album": "Meet the Orphans"},
    {"song": "La Camisa Negra", "artist": "Juanes", "album": "Mi Sangre"},
    {"song": "Umbrella", "artist": "Rihanna", "album": "Good Girl Gone Bad"},
    {"song": "Single Ladies", "artist": "Beyoncé", "album": "I Am... Sasha Fierce"},
    {"song": "Poker Face", "artist": "Lady Gaga", "album": "The Fame"},
    {"song": "Rolling in the Deep", "artist": "Adele", "album": "21"},
    {"song": "Hey Ya!", "artist": "OutKast", "album": "Speakerboxxx/The Love Below"},
    {"song": "In the End", "artist": "Linkin Park", "album": "Hybrid Theory"},
    {"song": "Numb", "artist": "Linkin Park", "album": "Meteora"},
    {"song": "Boulevard of Broken Dreams", "artist": "Green Day", "album": "American Idiot"},
    {"song": "American Idiot", "artist": "Green Day", "album": "American Idiot"},
    {"song": "Mr. Brightside", "artist": "The Killers", "album": "Hot Fuss"},
    {"song": "Clocks", "artist": "Coldplay", "album": "A Rush of Blood to the Head"},
    {"song": "Fix You", "artist": "Coldplay", "album": "X&Y"},
    {"song": "Yellow", "artist": "Coldplay", "album": "Parachutes"},
    {"song": "Lose Yourself", "artist": "Eminem", "album": "Curtain Call: The Hits"},
    {"song": "Stan", "artist": "Eminem", "album": "The Marshall Mathers LP"},
    {"song": "Without Me", "artist": "Eminem", "album": "The Eminem Show"},
    {"song": "I Gotta Feeling", "artist": "Black Eyed Peas", "album": "The E.N.D."},
    {"song": "Where Is the Love?", "artist": "Black Eyed Peas", "album": "Elephunk"},
    {"song": "Toxic", "artist": "Britney Spears", "album": "In the Zone"},
    {"song": "Baby One More Time", "artist": "Britney Spears", "album": "...Baby One More Time"},
    {"song": "Genie in a Bottle", "artist": "Christina Aguilera", "album": "Christina Aguilera"},
    {"song": "Complicated", "artist": "Avril Lavigne", "album": "Let Go"},
    {"song": "Sk8er Boi", "artist": "Avril Lavigne", "album": "Let Go"},
    {"song": "Viva La Vida", "artist": "Coldplay", "album": "Viva la Vida or Death and All His Friends"},
    {"song": "Feel Good Inc.", "artist": "Gorillaz", "album": "Demon Days"},

    {"song": "Shape of You", "artist": "Ed Sheeran", "album": "Divide"},
    {"song": "Blinding Lights", "artist": "The Weeknd", "album": "After Hours"},
    {"song": "Uptown Funk", "artist": "Mark Ronson ft. Bruno Mars", "album": "Uptown Special"},
    {"song": "Happy", "artist": "Pharrell Williams", "album": "Girl"},
    {"song": "Royals", "artist": "Lorde", "album": "Pure Heroine"},
    {"song": "Counting Stars", "artist": "OneRepublic", "album": "Native"},
    {"song": "Radioactive", "artist": "Imagine Dragons", "album": "Night Visions"},
    {"song": "Demons", "artist": "Imagine Dragons", "album": "Night Visions"},
    {"song": "Believer", "artist": "Imagine Dragons", "album": "Evolve"},
    {"song": "Thunder", "artist": "Imagine Dragons", "album": "Evolve"},
    {"song": "Senorita", "artist": "Shawn Mendes & Camila Cabello", "album": "Single"},
    {"song": "Havana", "artist": "Camila Cabello", "album": "Camila"},
    {"song": "Bad Guy", "artist": "Billie Eilish", "album": "When We All Fall Asleep, Where Do We Go?"},
    {"song": "Levitating", "artist": "Dua Lipa", "album": "Future Nostalgia"},
    {"song": "Don't Start Now", "artist": "Dua Lipa", "album": "Future Nostalgia"},
    {"song": "Peaches", "artist": "Justin Bieber", "album": "Justice"},
    {"song": "Sorry", "artist": "Justin Bieber", "album": "Purpose"},
    {"song": "Love Yourself", "artist": "Justin Bieber", "album": "Purpose"},
    {"song": "Stay", "artist": "The Kid LAROI & Justin Bieber", "album": "Single"},
    {"song": "Industry Baby", "artist": "Lil Nas X", "album": "Montero"},
    {"song": "Old Town Road", "artist": "Lil Nas X", "album": "7 EP"},
    {"song": "Sunflower", "artist": "Post Malone & Swae Lee", "album": "Hollywood's Bleeding"},
    {"song": "Circles", "artist": "Post Malone", "album": "Hollywood's Bleeding"},
    {"song": "Rockstar", "artist": "Post Malone", "album": "Beerbongs & Bentleys"},
    {"song": "God's Plan", "artist": "Drake", "album": "Scorpion"},
    {"song": "One Dance", "artist": "Drake", "album": "Views"},
    {"song": "Hotline Bling", "artist": "Drake", "album": "Views"},
    {"song": "Sicko Mode", "artist": "Travis Scott", "album": "Astroworld"},
    {"song": "Goosebumps", "artist": "Travis Scott", "album": "Birds in the Trap Sing McKnight"},
    {"song": "HUMBLE.", "artist": "Kendrick Lamar", "album": "DAMN."},
    {"song": "Alright", "artist": "Kendrick Lamar", "album": "To Pimp a Butterfly"},
    {"song": "DNA.", "artist": "Kendrick Lamar", "album": "DAMN."},
    {"song": "Stronger", "artist": "Kanye West", "album": "Graduation"},
    {"song": "Gold Digger", "artist": "Kanye West", "album": "Late Registration"},
    {"song": "Heartless", "artist": "Kanye West", "album": "808s & Heartbreak"},
    {"song": "Firework", "artist": "Katy Perry", "album": "Teenage Dream"},
    {"song": "Roar", "artist": "Katy Perry", "album": "Prism"},
    {"song": "Dark Horse", "artist": "Katy Perry", "album": "Prism"},
    {"song": "Shake It Off", "artist": "Taylor Swift", "album": "1989"},
    {"song": "Blank Space", "artist": "Taylor Swift", "album": "1989"},
    {"song": "Love Story", "artist": "Taylor Swift", "album": "Fearless"},
    {"song": "Bad Blood", "artist": "Taylor Swift", "album": "1989"},
    {"song": "Someone Like You", "artist": "Adele", "album": "21"},
    {"song": "Hello", "artist": "Adele", "album": "25"},
    {"song": "Set Fire to the Rain", "artist": "Adele", "album": "21"},
    {"song": "Rolling Stones", "artist": "The Weeknd", "album": "Thursday"},
    {"song": "Hallowed Be Thy  Name", "artist": "Iron maiden", "album": "The number of the beast"}
]